[build]
  publish = "dist/spa"
  command = "yarn build"

[context.production.environment]
  APP_NAME="LegalCoin"
  DEVELOPMENT="false"
  NETWORK_CHAIN_ID="4667b205c6838ef70ff7988f6e8257e8be0e1284a2f59699054a018f743b1d11"
  NETWORK_HOST="telos.caleos.io"
  NETWORK_PORT="443"
  NETWORK_PROTOCOL="https"
  NETWORK_EXPLORER="https://explorer.telos.net/"
  HYPERION_ENDPOINT="https://telos.caleos.io"
  ISSUER_API_ENDPOINT="https://tokenissuer.y-knot.io"
  ACCOUNTS_API_ENDPOINT="https://ya.y-knot.io/api/graphql"
  ATOMICASSETS_API_ENDPOINT="https://atomic-telos.y-knot.io"
  IPFS_ENDPOINT="https://ipfs.y-knot.io"
  AA_ACCOUNT="admin.lc"
  AA_BUYBACK_ACCOUNT="factory.lc"
  ATOMICMARKET="market.yknot"
  LC_CONTRACT="token.lc"
  LC_SYMBOL="LEGAL"
  LC_PRECISION="2"

[context.develop.environment]
  APP_NAME="LegalCoin"
  DEVELOPMENT="true"
  NETWORK_CHAIN_ID="1eaa0824707c8c16bd25145493bf062aecddfeb56c736f6ba6397f3195f33c9f"
  NETWORK_HOST="testnet.telos.africa"
  NETWORK_PORT="443"
  NETWORK_PROTOCOL="https"
  NETWORK_EXPLORER="https://explorer-test.telos.net/"
  HYPERION_ENDPOINT="https://testnet.telos.africa"
  ISSUER_API_ENDPOINT="https://tokenissuer.dev.y-knot.io"
  ISSUER_SECRET="oi"
  ACCOUNTS_API_ENDPOINT="https://ya.dev.y-knot.io/api/graphql"
  ATOMICASSETS_API_ENDPOINT="https://atomic-telostest.y-knot.io"
  IPFS_ENDPOINT="https://ipfs.y-knot.io"
  AA_ACCOUNT="admin.lc"
  AA_BUYBACK_ACCOUNT="factory.lc"
  ATOMICMARKET="market.yknot"
  LC_CONTRACT="token.lc"
  LC_SYMBOL="LEGAL"
  LC_PRECISION="2"

[context.deploy-preview.environment]
  APP_NAME = "Telos Block Explorer"
  NODE_VERSION = "14"
  NETWORK_CHAIN_ID = "4667b205c6838ef70ff7988f6e8257e8be0e1284a2f59699054a018f743b1d11"
  NETWORK_HOST = "telos.caleos.io"
  NETWORK_PORT = "443"
  NETWORK_PROTOCOL = "https"
  NETWORK_EVM_RPC = "https://mainnet.telos.net/evm"
  NETWORK_EVM_ENDPOINT = "https://mainnet.telos.net"
  NETWORK_EVM_CONTRACT = "eosio.evm"
  NETWORK_EVM_CHAIN_ID = "40"
  HYPERION_ENDPOINT = "https://mainnet.telos.net"
  PRODUCER_BUCKET_URL="https://telos-producer-validation.s3.amazonaws.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
