name: Deploy Development

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Yarn
        run: |
          npm install --global yarn
          echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: Setup Environment
        run: cp .env.dev .env

      - name: Install Node Modules
        run: yarn

      - name: Build
        run: yarn run build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: y-knot.io
          username: dev@y-knot.io
          password: ${{ secrets.YKNOT_FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./dist/spa/
          server-dir: dev-legalcoin.y-knot.io/
